### ISSUE TITLE
Upload example output of generated files?

### ISSUE THREAD

**Issue by b-long** [eguneys/generator-emberfs#7]
In order to support development of this generator, it'd be nice to see what the reference output is _supposed_ to look like.  Any objection to posting the output files somewhere?

**Comment by b-long** [comment]
@noodles @jdmarshall @enjine @tahniyatkazmi Would any of you have this information?

**Comment by eguneys** [comment]
https://github.com/eguneys/gulp-ember-requirejs, this is the template I used to create this generator.

**Comment by b-long** [comment]
Awesome, thanks @eguneys !
